alias: Alarme Sécurité - Réinitialisation Mode Manuel
description: >-
  Réinitialise le blocage manuel quand Rayman arrive à la maison pendant les
  heures de désactivation
triggers:
  - entity_id:
      - person.rayman_2
    to: home
    from: not_home
    trigger: state
  - at: input_datetime.securite_heure_desactivation
    trigger: time
conditions:
  - condition: state
    entity_id: person.rayman_2
    state: home
  - condition: template
    value_template: >
      {% set heure_activation = states('input_datetime.securite_heure_activation') %}
      {% set heure_desactivation = states('input_datetime.securite_heure_desactivation') %}
      {% set heure_actuelle = now().strftime('%H:%M:%S') %}

      {# Plage à cheval sur minuit (ex: 23:00:00 -> 07:00:00) :
         la plage de désactivation est 07:00:00 -> 23:00:00 #}
      {% if heure_activation > heure_desactivation %}
        {{ heure_actuelle >= heure_desactivation and heure_actuelle < heure_activation }}
      {# Plage sur la même journée (ex: 06:00:00 -> 22:00:00) :
         la plage de désactivation est avant 06:00:00 ou après 22:00:00 #}
      {% else %}
        {{ heure_actuelle < heure_activation or heure_actuelle >= heure_desactivation }}
      {% endif %}
actions:
  - action: input_boolean.turn_off
    metadata: {}
    target:
      entity_id:
        - input_boolean.statut_alarme_securite
        - input_boolean.securite_blocage_manuel_actif
    data: {}
  - action: script.discord_notification_personnalisee
    metadata: {}
    data:
      couleur: success
      channel_id: "1459865652679675915"
      message: Mode manuel désactivé. L'automatisation reprend le contrôle.
      titre: Alarme Sécurité - Réinitialisation Mode Manuel
  - delay:
      seconds: 2
  - target:
      entity_id: automation.alarme_securite_activation_automatique
    data:
      skip_condition: false
    action: automation.trigger
mode: single