alias: Discord - Mouvement Nuit avec Photo
description: Envoie une photo sur Discord lors d'un mouvement détecté quand l'alarme est active
triggers:
  - entity_id: binary_sensor.salon_person_occupancy
    to: "on"
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.statut_alarme_securite
    state: "on"
actions:
  - action: camera.snapshot
    metadata: {}
    target:
      entity_id: camera.salon
    data:
      filename: /config/www/cams/snapshot.jpg
  - action: script.discord_notification_personnalisee
    metadata: {}
    data:
      couleur: warning
      channel_id: "1459865652679675915"
      titre: "👁️ Mouvement Détecté"
      message: >
        **Localisation** : Salon
        **Heure** : {{ now().strftime('%H:%M:%S') }}
        **Personnes détectées** : {{ states('sensor.salon_person_count') }}
mode: single